services:
  qad-node1:
    build: .
    container_name: qad-node1
    ports:
      - "8080:8080"    # HTTP port
    restart: always
    environment:
      NODE_NAME: "qad-node1"
      HTTP_PORT: "8080"
      GRPC_PORT: "9876"
      CLUSTER_PORT: "7946"
      LOG_LEVEL: "debug"
      STORAGE_SIZE: "1000000000"
      EVICTION_ALGORITHM: "FIFO"
      SEED_NODES: ""
    networks:
      - qad-network

  qad-node2:
    build: .
    container_name: qad-node2
    ports:
      - "8081:8080"    # HTTP port
    restart: always
    environment:
      NODE_NAME: "qad-node2"
      HTTP_PORT: "8080"
      GRPC_PORT: "9876"
      CLUSTER_PORT: "7946"
      LOG_LEVEL: "debug"
      STORAGE_SIZE: "1000000000"
      EVICTION_ALGORITHM: "LRU"
      SEED_NODES: "qad-node1:7946"
    networks:
      - qad-network

  qad-node3:
    build: .
    container_name: qad-node3
    ports:
      - "8082:8080"    # HTTP port
    restart: always
    environment:
      NODE_NAME: "qad-node3"
      HTTP_PORT: "8080"
      GRPC_PORT: "9876"
      CLUSTER_PORT: "7946"
      LOG_LEVEL: "debug"
      STORAGE_SIZE: "1000000000"
      EVICTION_ALGORITHM: "FIFO"
      SEED_NODES: "qad-node1:7946,qad-node2:7946"
    networks:
      - qad-network

networks:
  qad-network:
    driver: bridge
